# Generated by Django 5.2.7 on 2025-11-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('range_km', models.PositiveIntegerField()),
                ('battery_capacity', models.CharField(max_length=50)),
                ('top_speed', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='bikes/')),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
