# Generated by Django 5.2.6 on 2025-11-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_bikebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('variant', models.CharField(default='Standard', max_length=50)),
                ('address', models.TextField()),
                ('payment_mode', models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payment')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.bike')),
            ],
        ),
    ]
