# Generated by Django 5.2.7 on 2025-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0010_booking_delete_bikebooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
