# Generated by Django 5.2.7 on 2025-11-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0011_booking_city_booking_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
